development:
  adapter: postgresql
  encoding: utf8
  database: homework_workflow_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: homework_workflow_test
  pool: 5

production:  
  adapter: postgresql
  encoding: utf8
  database: homework_workflow
  pool: 5